# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16I6r41swvTgdYKHbdU9llAsdf6s3u8jC
"""

from google.colab import files
uploaded = files.upload()  # select svm_wine_all_kernels.pkl

import pickle

with open('svm_wine_all_kernels.pkl', 'rb') as f:
    all_models = pickle.load(f)