# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16I6r41swvTgdYKHbdU9llAsdf6s3u8jC
"""

import streamlit as st
import pickle
import numpy as np

# ------------------------
# Load trained SVM models
# ------------------------
with open('svm_wine_all_kernels.pkl', 'rb') as f:
    all_models = pickle.load(f)

# ------------------------
# Streamlit App UI
# ------------------------
st.title("Wine Quality Predictor")

st.write("Enter the wine features below to predict quality (0 = Low, 1 = High)")

# Input fields for 11 features
fixed_acidity = st.number_input("Fixed Acidity", value=7.0)
volatile_acidity = st.number_input("Volatile Acidity", value=0.27)
citric_acid = st.number_input("Citric Acid", value=0.36)
residual_sugar = st.number_input("Residual Sugar", value=20.7)
chlorides = st.number_input("Chlorides", value=0.045)
free_sulfur_dioxide = st.number_input("Free Sulfur Dioxide", value=45)
total_sulfur_dioxide = st.number_input("Total Sulfur Dioxide", value=170)
density = st.number_input("Density", value=1.001)
pH = st.number_input("pH", value=3.0)
sulphates = st.number_input("Sulphates", value=0.45)
alcohol = st.number_input("Alcohol", value=8.8)

# Kernel selection
kernel = st.selectbox("Select SVM Kernel", options=["linear", "poly", "rbf"])

# Prediction
if st.button("Predict"):
    features = [fixed_acidity, volatile_acidity, citric_acid, residual_sugar,
                chlorides, free_sulfur_dioxide, total_sulfur_dioxide,
                density, pH, sulphates, alcohol]

    model = all_models[kernel]
    pred = model.predict([features])[0]
    prob = model.predict_proba([features])[0]

    st.success(f"Predicted Quality Class: {pred}")
    st.info(f"Probability -> Low: {prob[0]:.2f}, High: {prob[1]:.2f}")